# HalalBot Fly.io Configuration

app = "halalbot-alpha"
primary_region = "iad"  # Washington DC - good for US East Coast

[build]
  # Use the Dockerfile in the current directory

[env]
  # Streamlit configuration
  STREAMLIT_SERVER_PORT = "8501"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # 1GB RAM for FAISS and sentence-transformers

[mounts]
  # Mount for persistent data storage
  source = "halalbot_data"
  destination = "/app/data"

# Optional: Add secrets for sensitive data
# Run: fly secrets set SECRET_NAME=value
# [env]
#   ADMIN_EMAIL = "your-admin@email.com"